/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.SPham;

import BUS.KhuyenMaiBUS;
import BUS.SanPhamBUS;
import BUS.ThuongHieuBUS;
import DAO.DungTichDAO;
import DAO.NotHuongDAO;
import DTO.KhuyenMaiDTO;
import DTO.NotHuongDTO;
import DTO.SanPhamDTO;
import GUI.SanPham;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author hoang
 */
public class ThemSanPham extends javax.swing.JPanel {

    private String selectedFileName;
    /**
     * Creates new form ThemSanPham
     */
    public ThemSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOne = new javax.swing.JPanel();
        pnlCenter = new javax.swing.JPanel();
        anhSanPham = new javax.swing.JPanel();
        lblAnhSanPham = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        txttensp = new javax.swing.JTextField();
        lblKho = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        cbbthuonghieu = new javax.swing.JComboBox<>();
        lblXuatXu = new javax.swing.JLabel();
        lblLoai = new javax.swing.JLabel();
        cbbkhuyenmai = new javax.swing.JComboBox<>();
        lblThuongHieu = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        txtgianhap = new javax.swing.JTextField();
        lblGiaNhap = new javax.swing.JLabel();
        txtgiaban = new javax.swing.JTextField();
        lblGiaXuat = new javax.swing.JLabel();
        btnluusanpham = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cbbgioitinh = new javax.swing.JComboBox<>();
        cbbnongdo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbbdungtich = new javax.swing.JComboBox<>();
        txtnotdau = new javax.swing.JTextField();
        txtnotgiua = new javax.swing.JTextField();
        txtnotcuoi = new javax.swing.JTextField();
        btnchonnotdau = new javax.swing.JButton();
        btnchonnotgiua = new javax.swing.JButton();
        btnchonnotcuoi = new javax.swing.JButton();
        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));

        anhSanPham.setPreferredSize(new java.awt.Dimension(330, 240));

        lblAnhSanPham.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout anhSanPhamLayout = new javax.swing.GroupLayout(anhSanPham);
        anhSanPham.setLayout(anhSanPhamLayout);
        anhSanPhamLayout.setHorizontalGroup(
            anhSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anhSanPhamLayout.createSequentialGroup()
                .addComponent(lblAnhSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        anhSanPhamLayout.setVerticalGroup(
            anhSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnhSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        lblTenSP.setText("Tên sản phẩm");

        lblKho.setText("Giới tính");

        lblSize.setText("Dung tích");

        lblXuatXu.setText("Khuyến mãi");

        lblLoai.setText("Nồng độ");

        lblThuongHieu.setText("Thương hiệu");

        btnChonAnh.setText("Chọn hình ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        lblGiaNhap.setText("Giá nhập");

        lblGiaXuat.setText("Giá bán");

        btnluusanpham.setBackground(new java.awt.Color(0, 102, 204));
        btnluusanpham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnluusanpham.setText("Lưu");
        btnluusanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluusanphamActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 0, 102));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Hủy bỏ");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cbbgioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Unisex" }));
        cbbgioitinh.setToolTipText("");

        cbbnongdo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parfum", "EDP", "EDT", "EDC", "Eau Fraiche", "Aftershave" }));

        jLabel1.setText("Nốt đầu");

        jLabel2.setText("Nốt giữa");

        jLabel3.setText("Nốt cuối");

        txtnotdau.setBackground(new java.awt.Color(255, 255, 255));

        txtnotgiua.setBackground(new java.awt.Color(255, 255, 255));

        txtnotcuoi.setBackground(new java.awt.Color(255, 255, 255));

        btnchonnotdau.setText("jButton1");
        btnchonnotdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonnotdauActionPerformed(evt);
            }
        });

        btnchonnotgiua.setText("jButton1");
        btnchonnotgiua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonnotgiuaActionPerformed(evt);
            }
        });

        btnchonnotcuoi.setText("jButton1");
        btnchonnotcuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonnotcuoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addComponent(btnluusanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(anhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblXuatXu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKho, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenSP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttensp)
                            .addComponent(cbbkhuyenmai, 0, 149, Short.MAX_VALUE)
                            .addComponent(cbbgioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblGiaNhap, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtgianhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbnongdo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbthuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLoai)
                                    .addComponent(lblThuongHieu)))))
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addComponent(lblSize)
                                .addGap(116, 116, 116))
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addComponent(cbbdungtich, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblGiaXuat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtgiaban, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnotdau)
                            .addComponent(txtnotgiua)
                            .addComponent(txtnotcuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnchonnotdau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnchonnotgiua, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnchonnotcuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlCenterLayout.createSequentialGroup()
                                        .addComponent(lblTenSP)
                                        .addGap(4, 4, 4)
                                        .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlCenterLayout.createSequentialGroup()
                                        .addComponent(lblGiaNhap)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addComponent(lblSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbdungtich, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addComponent(lblGiaXuat)
                                .addGap(4, 4, 4)
                                .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKho, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLoai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addComponent(cbbgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblXuatXu)
                                .addGap(39, 39, 39))
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addComponent(cbbnongdo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblThuongHieu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbbthuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbkhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(anhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtnotdau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnluusanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlCenterLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnotgiua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnchonnotgiua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))))
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addComponent(btnchonnotdau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnotcuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnchonnotcuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );

        pnlTop.setBackground(new java.awt.Color(204, 51, 0));

        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("THÊM SẢN PHẨM MỚI");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelOneLayout = new javax.swing.GroupLayout(panelOne);
        panelOne.setLayout(panelOneLayout);
        panelOneLayout.setHorizontalGroup(
            panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelOneLayout.setVerticalGroup(
            panelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOneLayout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnluusanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluusanphamActionPerformed
        try {
            // ==== Kiểm tra dữ liệu nhập ====
            String tenSP = txttensp.getText().trim();
            if (tenSP.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên sản phẩm không được để trống!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int gianhap;
            int giaban;

            try {
                gianhap = Integer.parseInt(txtgianhap.getText().trim());
                if (gianhap <= 0) {
                    JOptionPane.showMessageDialog(this, "Giá nhập phải là số nguyên dương!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Giá nhập không hợp lệ!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                giaban = Integer.parseInt(txtgiaban.getText().trim());
                if (giaban <= 0) {
                    JOptionPane.showMessageDialog(this, "Giá bán phải là số nguyên dương!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Giá bán không hợp lệ!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // ==== Tạo đối tượng DTO ====
            SanPhamDTO dto = new SanPhamDTO();

            dto.setName(tenSP);
            dto.setSex((String) cbbgioitinh.getSelectedItem());
            dto.setImages(selectedFileName);
            dto.setConcentration((String) cbbnongdo.getSelectedItem());

            String tenTH = (String) cbbthuonghieu.getSelectedItem();
            int brandId = ThuongHieuBUS.getInstance().getIdByName(tenTH);
            dto.setBrandId(brandId);

            String tenKM = (String) cbbkhuyenmai.getSelectedItem();
            int promoId = KhuyenMaiBUS.getInstance().getIdByName(tenKM);
            dto.setPromotionId(promoId);

            int volumeSize = Integer.parseInt((String) cbbdungtich.getSelectedItem());
            int volumeId = DungTichDAO.getInstance().getIdBySize(volumeSize);
            dto.setVolumeId(volumeId);
            dto.setVolumeSize(volumeSize);

            dto.setCost(gianhap);
            dto.setPrice(giaban);
            dto.setStock(0);

            dto.setTopNotes(Arrays.asList(txtnotdau.getText().split("\\s*,\\s*")));
            dto.setHeartNotes(Arrays.asList(txtnotgiua.getText().split("\\s*,\\s*")));
            dto.setBaseNotes(Arrays.asList(txtnotcuoi.getText().split("\\s*,\\s*")));

            boolean success = SanPhamBUS.getInstance().saveFullSanPham(dto);

            if (success) {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
                Window window = SwingUtilities.getWindowAncestor(this);
                if (window instanceof JFrame) {
                    window.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnluusanphamActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn ảnh sản phẩm");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Ảnh JPG", "jpg");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String fileName = selectedFile.getName();

            // Chỉ nhận ảnh .jpg
            if (!fileName.toLowerCase().endsWith(".jpg")) {
                JOptionPane.showMessageDialog(this, "Chỉ hỗ trợ tệp .jpg!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Copy ảnh vào thư mục src/img_product
            File destination = new File("src/img_product/" + fileName);
            try {
                Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi sao chép ảnh!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
                return;
            }
            // Gán tên file để lưu vào DB khi nhấn Lưu
            selectedFileName = fileName;

            // Hiển thị ảnh vừa chọn
            ImageIcon icon = new ImageIcon(destination.getAbsolutePath());
            Image scaled = icon.getImage().getScaledInstance(lblAnhSanPham.getWidth(), lblAnhSanPham.getHeight(), Image.SCALE_SMOOTH);
            lblAnhSanPham.setIcon(new ImageIcon(scaled));
        }
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void btnchonnotdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonnotdauActionPerformed
        NoteSelectorDialog dialog = new NoteSelectorDialog((JFrame) SwingUtilities.getWindowAncestor(this));
        dialog.setVisible(true);
        List<String> newNotes = dialog.getSelectedNotes();

        if (newNotes != null && !newNotes.isEmpty()) {
            String currentText = txtnotdau.getText().trim();
            List<String> currentNotes = new ArrayList<>();

            if (!currentText.isEmpty()) {
                // Tách theo dấu ',' và loại bỏ khoảng trắng thừa
                for (String note : currentText.split(",")) {
                    currentNotes.add(note.trim());
                }
            }

            // Thêm các nốt mới nếu chưa có
            for (String newNote : newNotes) {
                if (!currentNotes.contains(newNote)) {
                    currentNotes.add(newNote);
                }
            }

            txtnotdau.setText(String.join(", ", currentNotes));
        }
    }//GEN-LAST:event_btnchonnotdauActionPerformed

    private void btnchonnotgiuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonnotgiuaActionPerformed
        NoteSelectorDialog dialog = new NoteSelectorDialog((JFrame) SwingUtilities.getWindowAncestor(this));
        dialog.setVisible(true);
        List<String> newNotes = dialog.getSelectedNotes();

        if (newNotes != null && !newNotes.isEmpty()) {
            String currentText = txtnotgiua.getText().trim();
            List<String> currentNotes = new ArrayList<>();

            if (!currentText.isEmpty()) {
                // Tách theo dấu ',' và loại bỏ khoảng trắng thừa
                for (String note : currentText.split(",")) {
                    currentNotes.add(note.trim());
                }
            }

            // Thêm các nốt mới nếu chưa có
            for (String newNote : newNotes) {
                if (!currentNotes.contains(newNote)) {
                    currentNotes.add(newNote);
                }
            }

            txtnotgiua.setText(String.join(", ", currentNotes));
        }
    }//GEN-LAST:event_btnchonnotgiuaActionPerformed

    private void btnchonnotcuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonnotcuoiActionPerformed
        NoteSelectorDialog dialog = new NoteSelectorDialog((JFrame) SwingUtilities.getWindowAncestor(this));
        dialog.setVisible(true);
        List<String> newNotes = dialog.getSelectedNotes();

        if (newNotes != null && !newNotes.isEmpty()) {
            String currentText = txtnotcuoi.getText().trim();
            List<String> currentNotes = new ArrayList<>();

            if (!currentText.isEmpty()) {
                // Tách theo dấu ',' và loại bỏ khoảng trắng thừa
                for (String note : currentText.split(",")) {
                    currentNotes.add(note.trim());
                }
            }

            // Thêm các nốt mới nếu chưa có
            for (String newNote : newNotes) {
                if (!currentNotes.contains(newNote)) {
                    currentNotes.add(newNote);
                }
            }

            txtnotcuoi.setText(String.join(", ", currentNotes));
        }
    }//GEN-LAST:event_btnchonnotcuoiActionPerformed

    public class NoteSelectorDialog extends JDialog {

        private JList<String> listNotes;
        private DefaultListModel<String> listModel;
        private JButton btnOk;
        private List<String> selectedNotes = new ArrayList<>();

        public NoteSelectorDialog(JFrame parent) {
            super(parent, "Chọn nốt hương", true);
            setSize(400, 300);
            setLocationRelativeTo(parent);

            listModel = new DefaultListModel<>();
            listNotes = new JList<>(listModel);
            listNotes.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
            JScrollPane scrollPane = new JScrollPane(listNotes);

            btnOk = new JButton("Chọn");
            btnOk.addActionListener(e -> {
                selectedNotes = listNotes.getSelectedValuesList();
                dispose();
            });

            add(scrollPane, BorderLayout.CENTER);
            add(btnOk, BorderLayout.SOUTH);
            loadNotes();
        }

        private void loadNotes() {
            NotHuongDAO dao = new NotHuongDAO();
            for (NotHuongDTO note : dao.getAllNotHuongs()) {
                listModel.addElement(note.getName());
            }
        }

        public List<String> getSelectedNotes() {
            return selectedNotes;
        }
    }

    public JComboBox<String> getCbbThuongHieu() {
        return cbbthuonghieu;
    }

    public JComboBox<String> getCbbKhuyenMai() {
        return cbbkhuyenmai;
    }

    public JComboBox<String> getCbbDungTich() {
        return cbbdungtich;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anhSanPham;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnchonnotcuoi;
    private javax.swing.JButton btnchonnotdau;
    private javax.swing.JButton btnchonnotgiua;
    private javax.swing.JButton btnluusanpham;
    private javax.swing.JComboBox<String> cbbdungtich;
    private javax.swing.JComboBox<String> cbbgioitinh;
    private javax.swing.JComboBox<String> cbbkhuyenmai;
    private javax.swing.JComboBox<String> cbbnongdo;
    private javax.swing.JComboBox<String> cbbthuonghieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAnhSanPham;
    private javax.swing.JLabel lblGiaNhap;
    private javax.swing.JLabel lblGiaXuat;
    private javax.swing.JLabel lblKho;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblThuongHieu;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblXuatXu;
    private javax.swing.JPanel panelOne;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtgianhap;
    private javax.swing.JTextField txtnotcuoi;
    private javax.swing.JTextField txtnotdau;
    private javax.swing.JTextField txtnotgiua;
    private javax.swing.JTextField txttensp;
    // End of variables declaration//GEN-END:variables

}
